### ISSUE TITLE
Identifying the license

### ISSUE THREAD

**Issue by willgmcc** [cofyc/dnscrypt-wrapper#100]
Hello,

It appears that the text in the COPYING file exactly matches [the ISC license](https://tldrlegal.com/license/-isc-license#fulltext), but the release notes for v0.2.2 instead say that this project switched from the GPLv2 license to BSD 0-Clause. That seems incorrect, since the [BSD 0-Clause license](https://tldrlegal.com/license/bsd-0-clause-license#fulltext) doesn't require the copying of the copyright and permission notices, but COPYING (and the ISC license) do. So, am I correct that the release note mentioning BSD 0-Clause is just an error, and that this project is instead released under the ISC license?

I ask only because I maintain the FreeBSD port of your project, and FreeBSD requires that I identify the license of your code, so I wanted to make sure that ISC is correct. Thanks for your help, and for all your work!

**Comment by cofyc** [comment]
Hi, @willgmcc 

Yes, the release note mentioning BSD 0-Clause is an error. I fixed it now (https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.2.2).

Thank you very much!
