### ISSUE TITLE
centos 7安装了4遍，没有任何错误就是无法使用。

### ISSUE THREAD

**Issue by likeclub** [cofyc/dnscrypt-wrapper#104]
唯一异常的就是执行这段命令后服务器不响应。
$ dnscrypt-wrapper --resolver-address=8.8.8.8:53 --listen-address=0.0.0.0:443 \
                   --provider-name=2.dnscrypt-cert.yechengfu.com \
                   --crypt-secretkey-file=1.key --provider-cert-file=1.cert

每步严格安装你的方法去执行，就是dns不通。防火墙也关闭了。

**Comment by cofyc** [comment]
@likeclub 能不能把你编译安装步骤和日志输出都贴一下？

**Comment by cofyc** [comment]
@likeclub 给出的信息太少，我先关闭 issue，有能给我下在 centos 7 重现问题的步骤，告知下。

0.3 版刚发布，可以使用最新代码测试。
