### ISSUE TITLE
configure: WARNING: was libsodium compiled with --enable-minimal

### ISSUE THREAD

**Issue by pysiak** [cofyc/dnscrypt-wrapper#107]
Saw this today. Is this just a precautionary warning or there is impact on dnscrypt-wrapper?

Bonus (perhaps related) question: what enables support for xchacha20?

**Comment by pysiak** [comment]
It seems that libsodium compiled without "--enable-minimal" gets me xchacha20 support.

**Comment by cofyc** [comment]
Yes, no harm ;-)
