### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by jedisct1** [cofyc/dnscrypt-wrapper#108]
Hi!

Version 0.2.2 was released a while back, and quite a lot of things happened since.

XChaCha20 support would be good to have, especially since Unbound just added support for it.

Do you think you could tag version 0.3.0 soon?

**Comment by cofyc** [comment]
Hi, @jedisct1 

Thanks for reminding me! [dnscrypt-wrapper 0.3](https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3) is released now.
