### ISSUE TITLE
dnscrypt-wrapper 0.3 does not accept documented syntax for key rotation

### ISSUE THREAD

**Issue by chrcoluk** [cofyc/dnscrypt-wrapper#109]
The documentation says to use this syntax when allowing both old and new key to work temporarily.

dnscrypt-wrapper --resolver-address=8.8.8.8:53 --listen-address=0.0.0.0:443 \
                   --provider-name=2.dnscrypt-cert.yechengfu.com \
                   --crypt-secretkey-file=1.key,2.key --provider-cert-file=2.cert

This worked fine in 1.2.0

I upgraded to 1.3.0 and now that syntax generates this error.

[24984] 17 Aug 05:30:28.290 [err] [main.c:287] could not match secret key 1 with a certificate.

I can successfully start by specifying both certificates like so.

dnscrypt-wrapper --resolver-address=8.8.8.8:53 --listen-address=0.0.0.0:443 \
                   --provider-name=2.dnscrypt-cert.yechengfu.com \
                   --crypt-secretkey-file=1.key,2.key --provider-cert-file=1.cert,2.cert

I dont know if this actually wont break anything tho.

So either there is a bug or documentation needs updating.

**Comment by chrcoluk** [comment]
Client log below which seems to have it choosing the new certificate, however I dont know what will happen yet on automated client rotation as this is after a manual client restart.

Aug 17 05:37:16 | dnscrypt-proxy | 54465 | Chosen certificate #1502944187 is valid from [2017-08-17] to [2017-08-18]
-- | -- | -- | --
Aug 17 05:37:16 | dnscrypt-proxy | 54465 | This certificate supersedes certificate #1502942760
Aug 17 05:37:16 | dnscrypt-proxy | 54465 | This certificate is valid
Aug 17 05:37:16 | dnscrypt-proxy | 54465 | Server certificate with serial #1502944187 received
Aug 17 05:37:16 | dnscrypt-proxy | 54465 | This certificate is valid
Aug 17 05:37:16 | dnscrypt-proxy | 54465 | Server certificate with serial #1502942760 received
Aug 17 05:37:16 | dnscrypt-proxy | 54465 | Done

I had to manually restart the client as once the server failed the tunnel went dead until I restarted client.

**Comment by chantra** [comment]
@chrcoluk this is related to jedisct1/dnscrypt-server-docker#38

I am not sure yet what the best way would be to tackle this. One way could be to mark some certs as non-publishable.

**Comment by chrcoluk** [comment]
I was offline earlier but I made 2 cron scripts to run one minute after rotation to check if dns was working.

root@test bind-tools # crontab -l      
16 8 * * * /usr/local/bin/nslookup google.fr. > /tmp/dnstest816
26 9 * * * /usr/local/bin/nslookup google.de. > /tmp/dnstest926

and looks like it works fine

root@test bind-tools # cat /tmp/dnstest816
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   google.fr
Address: 216.58.213.163
Name:   google.fr
Address: 2a00:1450:4007:811::2003

root@test bind-tools # cat /tmp/dnstest926
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   google.de
Address: 216.58.213.163
Name:   google.de
Address: 2a00:1450:4007:811::2003

So an easy fix would be to change the documentation to what I did, but I guess that depends if you find that ok or not.

**Comment by montvid** [comment]
Hi there, I am using this persons dnscrypt service and he has key rotation sorted [https://dnscrypt.pl/2017/02/26/how-key-rotation-is-automated/](https://dnscrypt.pl/2017/02/26/how-key-rotation-is-automated/)
Maybe this will help you?

**Comment by cofyc** [comment]
@chantra How should we fix this?

**Comment by chantra** [comment]
@cofyc I don't have a good answer. I have commented in https://github.com/jedisct1/dnscrypt-server-docker/issues/38#issuecomment-320518176 that there is currently no good way to find ES version from a client magic (or even a key for that matter).

https://github.com/jedisct1/dnscrypt-server-docker/issues/38#issuecomment-309989389 also has more details.

I would like to see a solution that is not heavily bound to an assumption on how the client_magic is built, or at least not that xchacha version's client_magic == xsalsa client magic + 1.

I thing I can think of is to not distribute some certs. e.g I may have old.cert and new.cert, and while I can still use old.cert for existing clients, we would only distribute new.cert as part of the TXT record, so new client will start using the new cert and eventually, the old cert will not be used anymore.
e.g maybe we could use something along: `--provider-cert-file=!1.cert,2.cert`, which would mean that cert `1.cert` would not be distributed.

cc @jedisct1 in case he has something else in mind.

**Comment by montvid** [comment]
@chantra so the solution in https://dnscrypt.pl/2017/02/26/how-key-rotation-is-automated/ is not good?

**Comment by cofyc** [comment]
@montvid Solution in your link is right way to rotate keys ([described in docs](https://github.com/cofyc/dnscrypt-wrapper#key-rotation)), but in 0.3 there is a bug in key rotation we need to fix.

**Comment by cofyc** [comment]
Closed via https://github.com/cofyc/dnscrypt-wrapper/commit/625f3119917f2820d9a6f7ce1a25c5ee35d7b235.
