### ISSUE TITLE
Change to key rotation every 24 hours

### ISSUE THREAD

**Issue by montvid** [cofyc/dnscrypt-wrapper#111]
Many servers I tried use 1 year rotating keys that are bad for forward secrecy. I think they use dnscrypt-wrapper defaults. Could the defaults be changed to 24 hours as per specification so everyone upgrading the wrapper will make their service more secure?

The problem is described in [https://github.com/jedisct1/dnscrypt-proxy/issues/520](https://github.com/jedisct1/dnscrypt-proxy/issues/520)

> [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
> dnscrypt-proxy will complain about PFS for anything more than 24 hours.

See this post for a practical example that works fine (I use this dns service with no problems) [https://dnscrypt.pl/2017/02/26/how-key-rotation-is-automated/](https://dnscrypt.pl/2017/02/26/how-key-rotation-is-automated/)

**Comment by cofyc** [comment]
Seems reasonable. I will update docs first suggesting user to generate short-term key pairs and use key-rotation mechanism.

**Comment by X8716e** [comment]
Use of ephemeral keys could possibly be used as a template as seen here: https://dnscrypt.is (d0wn's Icelandic servers).

**Comment by cofyc** [comment]
Docs was updated in https://github.com/cofyc/dnscrypt-wrapper/pull/113. I am not going to change the default value of `--cert-file-expire-days`, because it may violate user expectation.

**Comment by montvid** [comment]
@cofyc User expectation is safe default settings. The **protocol specification** has always recommended to keep/use a key for no more than 24 hours [comment here](https://github.com/jedisct1/dnscrypt-proxy/issues/520#issuecomment-269055748). The problem is between you and the people who created dnscrypt - not the users. The creators of dnscrypt put a warning into the code you choose to ignore. You think you know better than the creators of dnscrypt? Users depend on your default settings to be safe so if something bad happens they will blame you not dnscrypt as you don't use recommended defaults!!! I will definitely not use a service that has 1 key for 365 days because if it is compromised all the data of <=365 days is harvested!

@X8716e ephemeral keys use too much cpu on a standard openwrt router and https://dnscrypt.is does not have a 24h key rotation so I am not going to use it.

**Comment by cofyc** [comment]
@montvid Updated in https://github.com/cofyc/dnscrypt-wrapper/commit/9d0a7931b4dd088600f3843dcd11ae89c97af234.

**Comment by montvid** [comment]
Thanks a lot. Now lets hope more of the servers will implement it. Nice that jedisct1 is running one in France.
