### ISSUE TITLE
Upstream DNS over TLS

### ISSUE THREAD

**Issue by ricklahaye** [cofyc/dnscrypt-wrapper#117]
Any chance we can get DNS over TLS for upstream servers?

**Comment by cofyc** [comment]
@ricklahaye 
I don't have much time on this project. Any contributions are welcome!

**Comment by jedisct1** [comment]
Upstream server should be a local caching server. TLS should not be required between dnscrypt-wrapper and that caching server.

Unbound can be that caching server, and it supports DNS over TLS (which is useless for queries sent to authoritative servers).
