### ISSUE TITLE
dnscrypt-proxy Project Archived

### ISSUE THREAD

**Issue by snorkasaurus** [cofyc/dnscrypt-wrapper#119]
Greetings,

It seems the [jedisct1/dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) project was recently archived, making it read-only. A couple months ago jedisct1 created an issue asking for new maintainers but nobody seemed willing or able to take over ownership. The most pressing issue right now is probably that the public resolver list can no longer be updated and clients may end up trying to access dead or changed servers.

I have created an [issue here on my fork](https://github.com/snorkasaurus/dnscrypt-proxy/issues/7) in an attempt to create a place for users to discuss the future of the project (since a new issue obviously can not be opened on the original project page). If anyone has a better idea or is able to contact jedisct1 I am all ears.  Hopefully opening an issue here doesn't seem like an overreaction, I just don't know of another way to locate dnscrypt-proxy users and discuss the future of the project.

If this is really an inappropriate place to look for help please accept my sincere apologies.

Snork.

**Comment by cofyc** [comment]
I replied in https://github.com/snorkasaurus/dnscrypt-proxy/issues/7#issuecomment-354391430.
