### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jedisct1** [cofyc/dnscrypt-wrapper#132]
Hi @cofyc 

Could you tag a new release soon?

[This](https://github.com/cofyc/dnscrypt-wrapper/pull/130) probably justifies a new release, as well as displaying the stamps after a new key pair has been created.

**Comment by jedisct1** [comment]
Ok, that's all I have for now :)

If you want to make a new release.

**Comment by cofyc** [comment]
Increased minor version and released [0.4.0](https://github.com/cofyc/dnscrypt-wrapper/tree/v0.4.0), see https://github.com/cofyc/dnscrypt-wrapper/blob/master/CHANGELOG.md#v040.

**Comment by cofyc** [comment]
Closed via https://github.com/cofyc/dnscrypt-wrapper/pull/136.
