### ISSUE TITLE
0.4.0 release tarball?

### ISSUE THREAD

**Issue by ilovezfs** [cofyc/dnscrypt-wrapper#137]
For https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3 there was a release tarball https://github.com/cofyc/dnscrypt-wrapper/releases/download/v0.3/dnscrypt-wrapper-v0.3.tar.bz2

For https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.4.0 I'm only seeing the source archive tarball https://github.com/cofyc/dnscrypt-wrapper/archive/v0.4.0.tar.gz

Is there going to be a release tarball for 0.4.0 or do you just want Homebrew to use the source archive tarball now?

**Comment by cofyc** [comment]
hi,
Previously, I used git submodules, so I need to include submodules' source in each release. But now I don't use submodules anymore, github source archive tarball should be enough. Please use the source archive tarball instead. If it does not work, let me know.

**Comment by ilovezfs** [comment]
Perfect. Thank you!

**Comment by ilovezfs** [comment]
@cofyc you may want to update your README accordingly as it still contemplates submodules.

**Comment by cofyc** [comment]
@ilovezfs 
Fixed in https://github.com/cofyc/dnscrypt-wrapper/pull/138. Thanks!

**Comment by ilovezfs** [comment]
>Fixed in #138.
So fast!

>Thanks
You're welcome :)
