### ISSUE TITLE
v4.0 multiple key issue

### ISSUE THREAD

**Issue by pysiak** [cofyc/dnscrypt-wrapper#139]
Ever since I upgraded from 0.2.2 to 0.4 (IIRC I skipped 0.3.0 because I've had the same issues) the setup cannot work with multiple keys.

What happens is when the wrapper is started with 1 key/cert pair everything works ok.

When the rotation happens and a 2nd key/cert is generated and wrapper is restarted to use both keys and both certs, it starts up and says will use the public key for both keys/certs (2 different fingerprints). But the clients (dnscrypt-proxy 1.9.4 as well as 2.0) stop working. They report they'll be using the latest key. On the wrapper side it complains about unauthenticated queries.

If I remove the old key from the wrapper and leave the latest one, it works again.

Any ideas what am I doing wrong?

**Comment by jedisct1** [comment]
Damn.

Can you revert f97ddc348c445f8b6013ff332554f5f97b476a7c ?

**Comment by jedisct1** [comment]
Ah, just noticed that you had the same issue with 0.3.0, so this is not it.

Can you try the `xchacha20-stamps` branch here? https://github.com/jedisct1/dnscrypt-wrapper/tree/xchacha-stamps

**Comment by pysiak** [comment]
I waited until the next reoccurence of the issue and when I saw it failing, I restarted using a binary with f97ddc3 reverted and it works now! Went back to the previous one, didn't, started again with the new one, it worked. 2 key/cert pairs are in the config.

My clients used for testing: are 2.0.0 on amd64 Ubuntu and 1.9.4 without xchacha20 support running on mips32 (OpenWrt).
Wrapper is on amd64 Debian.

**Comment by jedisct1** [comment]
I must confess that I don't totally understand how it works, but if it's broken, reverting https://github.com/cofyc/dnscrypt-wrapper/commit/f97ddc348c445f8b6013ff332554f5f97b476a7c looks the right thing to do until it is fixed :/

/cc @cofyc

**Comment by pysiak** [comment]
I will give a stab at filter_signed_certs()
I understand the objective is to discard old and future certs.
Any other objectives?

**Comment by cofyc** [comment]
@jedisct1 @pysiak 
I've done some tests and filed a PR (https://github.com/cofyc/dnscrypt-wrapper/pull/141) to fix. Could you take a look at?

**Comment by cofyc** [comment]
@pysiak https://github.com/cofyc/dnscrypt-wrapper/pull/141 is merged. Could you try latest master branch again?

**Comment by pysiak** [comment]
Hi, yes, it works! Thanks for looking into this
Did a few key rollovers, used more than 2 key/cert pairs. All running ok.
Thank you!

**Comment by jedisct1** [comment]
Thanks a lot @cofyc !
