### ISSUE TITLE
能否使用Ipv6地址？

### ISSUE THREAD

**Issue by JunShine** [cofyc/dnscrypt-wrapper#143]
像这样生成证书
dnscrypt-wrapper --gen-provider-keypair --provider-name=2.dnscrypt-cert.ClientDNS.com --ext-address=[111:222:XXX:xxx::1]:5354 --dnssec

启动dnscrypt-wrapper
dnscrypt-wrapper --resolver-address=8.8.8.8:53 --listen-address=[::]:5354 --provider-name=2.dnscrypt-cert.ClientDNS.com --crypt-secretkey-file=/root/dns-key-v6/Key.key --provider-cert-file=/root/dns-key-v6/Cert.cert -VVV -l /var/log/dnscrypt-wrapper-ipv6.log

客户端启动
dnscrypt-proxy1.9版的
dnscrypt-proxy --local-address=127.0.0.1:55 --resolver-address=[111:222:XXX:xxx::1]:5354 \
                --provider-name=2.dnscrypt-cert.ClientDNS.com \
                --provider-key=................
dnscrypt-proxy2.0版在配置文件修改sdns:链接并去掉注释
结果都是无法连接
Refetching server certificates
[ERROR] Unable to retrieve server certificates

尝试过换ipv4地址的话没问题的。不知道是我的命令输入有误，还是其他哪里出问题了呢？

**Comment by cofyc** [comment]
@JunShine 我没在 ipv6 环境里测试过，你是修复问题，还是放弃在 ipv6 下使用了？

**Comment by JunShine** [comment]
后来发现换强制TCP就可以了，不过延迟太大，放弃用了。
