### ISSUE TITLE
Intsall error

### ISSUE THREAD

**Issue by Betaman2k** [cofyc/dnscrypt-wrapper#146]
Heya
OS: Debian 9.4 ( 64 Bit )
dnscrypt-wrapper :0bff18d1d868ff5db90034c5662925145a254388  ( latest )
libsodium latest stable
libevent-2.1.8-stable 

I try to compile dnscrypt-wrapper but i get a error, dunno why, i hope u can help me

main.c: In function 'filter_signed_certs':
main.c:234:17: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                 if (ntohl(*(uint32_t *)filtered_certs[j].serial) < ntohl(*(uint32_t *)c->signed_certs[i].serial)) {
                 ^~
main.c:234:17: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
make[1]: Entering directory '/opt/sourcedns/dnscrypt-wrapper/argparse'
cc -o argparse.o -c -Wall -fPIC -O3 -g -ggdb argparse.c
ar rcs libargparse.a argparse.o
make[1]: Leaving directory '/opt/sourcedns/dnscrypt-wrapper/argparse'
  LINK dnscrypt-wrapper
main.o: In function `create_stamp':
/opt/sourcedns/dnscrypt-wrapper/main.c:433: undefined reference to `sodium_bin2base64'
collect2: error: ld returned 1 exit status
Makefile:194: recipe for target 'dnscrypt-wrapper' failed
make: *** [dnscrypt-wrapper] Error 1

**Comment by cofyc** [comment]
It seems like compiler cannot find `libsodium`. Please try `./configure --with-sodium=/path/to/your/sodium` to configure sodium path.
