### ISSUE TITLE
Ability to choose between TCP/UDP

### ISSUE THREAD

**Issue by drduh** [cofyc/dnscrypt-wrapper#147]
Is it possible to configure dnscrypt-wrapper to use either TCP or UDP - not both at the same time? It looks like the client supports TCP only, but not the server.

**Comment by jedisct1** [comment]
Unless you are using a very old version, it does support both TCP and UDP.

**Comment by drduh** [comment]
How do I choose between protocols, then? Is there a command line flag to pass to dnscrypt-wrapper?

**Comment by jedisct1** [comment]
This is a client setting.

**Comment by drduh** [comment]
Well I'm asking about the server, since I wish to have two services on the same port (UDP and TCP 443).

**Comment by drduh** [comment]
I know. I'm asking whether it's possible to make dnscrypt-wrapper *not* to listen on the same TCP port? Isn't UDP sufficient?

**Comment by cofyc** [comment]
It seems reasonable. I'm going to support this.
