### ISSUE TITLE
请教：在使用dnscrypt-proxy 2.x版本中，如果使用非443端口。

### ISSUE THREAD

**Issue by eedba** [cofyc/dnscrypt-wrapper#150]
我服务端在国外的vps上配置了dnscrypt-wrapper，端口使用的是非443端口。因为443要给网站使用，所以。。。

然后，在配置中，dnscrypt-wrapper 生成了一个sdns 参数。将它应用在 dnscrypt-proxy 2.x 中，却一直是timeout .看了一下日志，dnscrypt-proxy 2.x 在使用sdns 的时候连接的是443端口。请问这个有撒解决方案吗？

**Comment by cofyc** [comment]
@eedba 在生成 provider-keypair 时，需要指定 `--ext-address` 。这个里面需要配置你 dnscrypt-wrapper 服务器的公网 IP 和对外服务端口（也就是你说的非 443 端口）。
这样生成的 `sdns` 才是正确的。

**Comment by eedba** [comment]
哈哈。谢谢~
