### ISSUE TITLE
Log entry "Received a suspicious query from the client"

### ISSUE THREAD

**Issue by mibere** [cofyc/dnscrypt-wrapper#151]
Hello,

I'm using [jedisct1/dnscrypt-server-docker](https://github.com/jedisct1/dnscrypt-server-docker) for a public DNSCrypt server on port 443.

My Docker log is full of several hundreds entries

> [warning] [udp_request.c:351] Received a suspicious query from the client\n"

Is there a way for me to suppress this warning? 

1. it unnecessarily fills the log
2. I'm not interested in this information/warning

Maybe the warning has to do with HTTPS port 443 (I'm running a website at port 80 and 8443 on the same server too).

**Comment by jedisct1** [comment]
Indeed, the severity of this message should probably be down to `DEBUG`. Even over UDP, servers constantly receive a lot of crap/scans on all ports.

**Comment by cofyc** [comment]
Closed via https://github.com/cofyc/dnscrypt-wrapper/pull/152. Thanks!
