### ISSUE TITLE
[ERROR] Invalid provider key

### ISSUE THREAD

**Issue by theodotos** [cofyc/dnscrypt-wrapper#157]
Hello,

I get "Invalid provider key" when I run `dnscrypt-proxy` for testing the cert.

I generate the cert:

```
# ./dnscrypt-wrapper --gen-provider-keypair --provider-name=2.dnscrypt-cert.example.com --ext-address=1.1.1.1
```

Run the test:

```
# dnscrypt-proxy --local-address=127.0.0.1:55 --resolver-address=127.0.0.1:443 --provider-name=2.dnscrypt-cert.example.com --provider-key=public.key

Sun Aug  5 13:32:01 2018 [ERROR] Invalid provider key
```

Am I doing something wrong?

I followed the guide in README.md:

https://github.com/cofyc/dnscrypt-wrapper/blob/master/README.md

**Comment by jedisct1** [comment]
`--provider-key=public.key`

If my memory serves me correctly, you had to put the actual key here (a hex string), not a file.

But you really should use dnscrypt-proxy 2.x. now.

**Comment by theodotos** [comment]
What a fool! Sorry for the false alarm. And thanks for the advice. It seems that 2.0 is packaged for Debian sid. I'll give that a go.

**Comment by theodotos** [comment]
@jedisct1 Can I ask another clarification? I've noticed that dnscrypt-proxy 2.x can also be used as a dnscrypt server. When you suggested  to switch to dnscrypt-proxy 2.x. did you mean only the client (dnscrypt-proxy 1.9) or the server too (dnscrypt-wrapper)?
