### ISSUE TITLE
关于创建密钥对时的问题：创建密钥对时一定要使用域名吗？只使用IP是否可以？

### ISSUE THREAD

**Issue by chinanoahli** [cofyc/dnscrypt-wrapper#163]
我在参考[readme](https://github.com/cofyc/dnscrypt-wrapper#quick-start)时，发现生成密钥对时需要用到域名。
但我并没有将我手上的域名解释到我的服务器上，因为国内审核还是比较麻烦的。
请问生成密钥对需要用到域名的步骤可以用IP代替吗？

**Comment by cofyc** [comment]
如果你不将证书存放在域名 TXT 记录里，这个域名不需要真实存在。

**Comment by chinanoahli** [comment]
好的，我有空再试试。
