### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pysiak** [cofyc/dnscrypt-wrapper#20]
Hi,

my dnscrypt-wrapper crashed today. Sadly, I don't have a core dump or any logs. Haven't found anything in the system logs.
It's been up since Oct 20th or something. I'm going to enable core dumps and see if I catch it again, I don't thing it's OOM, probably something else.

Will keep you posted if I find anything.

**Comment by cofyc** [comment]
@hdid Please update to latest [0.3 release](https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3).
