### ISSUE TITLE
Segfault :(

### ISSUE THREAD

**Issue by d0wnblog** [cofyc/dnscrypt-wrapper#21]
Hi,
I updated today to the last version and tried to start dnscrypt-wrapper 4 times on 4 different ports...

Two times it's running but 3 times i got this issue... And yes there are only 4 ports...

[  429.524058] dnscrypt-wrappe[4965]: segfault at 91 ip 00000000004044bd sp 00007fff19fd6020 error 4 in dnscrypt-wrapper[400000+a000]
[  431.519669] dnscrypt-wrappe[4963]: segfault at 90 ip 00000000004044bd sp 00007fffbb460970 error 4 in dnscrypt-wrapper[400000+a000]
[  484.112097] dnscrypt-wrappe[4977]: segfault at 91 ip 00000000004044bd sp 00007fff13188bb0 error 4 in dnscrypt-wrapper[400000+a000]

**Comment by simonclausen** [comment]
I also had segfaults when running a current clone from master just now. But only when listening on IPV4. IPV6 was running without issue.

Upgrading to the newest libsodium seems to have fixed the issue.

**Comment by cofyc** [comment]
Please update to latest [0.3 release](https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3).
