### ISSUE TITLE
ubuntu 14.10 运行出错...

### ISSUE THREAD

**Issue by MiuKaShi** [cofyc/dnscrypt-wrapper#35]
全部重新安装了dnscrypt-wrapper，clone最新的版本，结果输入
./dnscrypt-wrapper  -r 8.8.8.8:53 -a 0.0.0.0:443  --crypt-secretkey-file=crypt_secret.key --crypt-publickey-file=crypt_public.key --provider-cert-file=dnscrypt.cert --provider-name=2.dnscrypt-cert.yechengfu.com
后就没响应了....求帮忙解决下

**Comment by Cofyc** [comment]
加 -VVV 有任何日志么？贴这里下。

**Comment by MiuKaShi** [comment]
root@localhost:~/dnscrypt-wrapper# ./dnscrypt-wrapper -r 8.8.8.8:53 -a 0.0.0.0:443 --crypt-secretkey-file=crypt_secret.key --crypt-publickey-file=crypt_public.key --provider-cert-file=dnscrypt.cert --provider-name=2.dnscrypt-cert.yechengfu.com -VVV
[8046] 02 Apr 16:33:16.291 [info] Crypt public key fingerprint: AA14:C82C:3F7C:637A:F9A4:A0E5:2A51:CCDD:BB93:7A90:B20F:CB2B:7428:F763:D23B:0B75
只显示了这些...

**Comment by Cofyc** [comment]
显示这些，程序就退出了？

如果没有，就是正常的，如果你想让进程后台运行，加上 -d 参数。

**Comment by Cofyc** [comment]
目前情况如何？

**Comment by MiuKaShi** [comment]
不行，openwrt上用的1.4.3-1版本的dnscrypt-proxy，怎么也连接不上，但是用官方的dns解析地址就能连上。也不知道是
dnscrypt-wrapper出问题了还是dnscrypt-proxy的问题

2015-06-20 22:55 GMT+08:00 Yecheng Fu <notifications@github.com>:

**Comment by cofyc** [comment]
Please update to latest [0.3 release](https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3).
