### ISSUE TITLE
编译失败，./configure检查库通过。

### ISSUE THREAD

**Issue by lixuy** [Cofyc/dnscrypt-wrapper#36]
[root@centos dnscrypt-wrapper]# make
  CC dnscrypt.o
In file included from dnscrypt.c:1:
dnscrypt.h:6:26: warning: event2/event.h: No such file or directory
dnscrypt.h:7:29: warning: event2/listener.h: No such file or directory
dnscrypt.h:8:32: warning: event2/bufferevent.h: No such file or directory
dnscrypt.h:9:27: warning: event2/buffer.h: No such file or directory
dnscrypt.h:10:25: warning: event2/util.h: No such file or directory
In file included from dnscrypt.h:74,
                 from dnscrypt.c:1:
udp_request.h:24: error: expected specifier-qualifier-list before 'evutil_socket_t'
In file included from dnscrypt.c:1:
dnscrypt.h:92: error: expected specifier-qualifier-list before 'ev_socklen_t'
dnscrypt.c: In function 'dnscrypt_hrtime':
dnscrypt.c:26: warning: implicit declaration of function 'evutil_gettimeofday'
dnscrypt.c: In function 'dnscrypt_key_to_fingerprint':
dnscrypt.c:45: warning: implicit declaration of function 'evutil_snprintf'
dnscrypt.c: In function 'dnscrypt_server_uncurve':
dnscrypt.c:186: error: 'struct context' has no member named 'crypt_secretkey'
dnscrypt.c: In function 'add_server_nonce':
dnscrypt.c:224: error: 'struct context' has no member named 'nonce_ts_last'
dnscrypt.c:225: error: 'struct context' has no member named 'nonce_ts_last'
dnscrypt.c:227: error: 'struct context' has no member named 'nonce_ts_last'
dnscrypt.c: In function 'dnscrypt_server_curve':
dnscrypt.c:266: error: 'struct context' has no member named 'crypt_secretkey'
make: *** [dnscrypt.o] Error 1

**Comment by lixuy** [comment]
[root@centos dnscrypt-wrapper]# ./configure
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gar... no
checking for ar... ar
checking for gtar... gtar
checking for event_base_new in -levent... yes
checking for sodium_init in -lsodium... yes
configure: creating ./config.status
config.status: creating config.mak.autogen
config.status: executing config.mak.autogen commands

Configuration summary:

    Support for event library: yes
    Support for sodium library: yes

**Comment by Cofyc** [comment]
hi,

你检查下 libevent 是否不是 libevent 2 版本。

我的 configure.ac 脚本没特别判断是版本 2，所以版本 1 可以通过检查，但编译不了。(https://github.com/Cofyc/dnscrypt-wrapper/commit/4aedb2b5a4c2bfd4b4815a2a29d2da4008650a4b)

你将 libevent 升级到 libevent 2，试试。

**Comment by lixuy** [comment]
感谢，yum install的是1.4.13-4.el6.i686，自己到官网下载编译安装，错误解决。
建议Installation注明下libevent 2.
