### ISSUE TITLE
bin versus sbin

### ISSUE THREAD

**Issue by willgmcc** [Cofyc/dnscrypt-wrapper#37]
While there may be situations where you would not start dnscrypt-wrapper as the root user, in most of the use cases I can imagine you would. Supporting this, the --listen-address option defaults to port 53 (which requires root to bind to) and I believe the --user option can only be used if you launch as root. Because of this, would it make more sense for dnscrypt-wrapper to install into the "sbin" directory rather than "bin"?

**Comment by Cofyc** [comment]
You are right, changed in https://github.com/Cofyc/dnscrypt-wrapper/commit/fc8126da472bcc7ad8eb2d6199ccdea63739dcd3.

Thanks for your suggestions :)
