### ISSUE TITLE
无法生成crypt_public.key

### ISSUE THREAD

**Issue by junife** [Cofyc/dnscrypt-wrapper#54]
我的系统是Centos 6 x86，根据http://03k.org/dnscrypt-wrapper-usage.html进行的操作。但是在命令行执行dnscrypt-wrapper --gen-crypt-keypair，显示如下：
Generate crypt key pair... ok.
Secret key stored in crypt_secret.key
无法生成crypt_public.key 。请各位朋友帮忙分析一下。

**Comment by Cofyc** [comment]
hi, 最新版不需要 public key 了。你需要参加下最新的 README.md 文档。

**Comment by junife** [comment]
谢谢回复 
我参照了，README.md。在Usagek中执行到3）的命令如下（注服务器的443端口被占用，改成6443）：
dnscrypt-wrapper --resolver-address=114.114.114.114:53 --listen-address=0.0.0.0:6443 \
                   --provider-name=2.dnscrypt-cert.yechengfu.com \
                   --crypt-secretkey-file=1.key --provider-cert-file=1.cert
但是，命令行好像死了，一直没有反馈结果。只有Ctrl+Z结束命令的执行。请问这是出了什么问题？

**Comment by Cofyc** [comment]
hi，默认是前台运行。如果你想让其后台运行。需要加 -d/--daemonize 参数。
