### ISSUE TITLE
Multiples instances of dnscrypt-wrapper

### ISSUE THREAD

**Issue by azalio** [Cofyc/dnscrypt-wrapper#56]
Hello!

Thank you for programm!

I try to run 2 instances of dnscrypt-wrapper, but get this message:
**[err] [udp_request.c:536] Unable to bind (UDP) [Address already in use]** for second instance.

How I can swith to a new configuration with zero downtime?
If I set a different listening port for dnscrypt-wrapper - clients don't know the new port.

Ubuntu 10.04.3 LTS
dnscrypt-wrapper --version
dnscrypt-wrapper 0.2.2.g6136535

**Comment by Cofyc** [comment]
Hi, @azalio 

Sorry, in your case there is no way to upgrade with zero downtime.

Only Linux kernel 3.9+ support SO_REUSEPORT option, which made it possible to run multiple processes on same port. (https://lwn.net/Articles/542629/)

**Comment by pysiak** [comment]
You can upgrade your kernel to 3.9 sitting on 10.04.3 LTS or you could upgrade to the next LTS which has 3.9+.

According to https://wiki.ubuntu.com/Kernel/FAQ it is 12.04.4

**Comment by azalio** [comment]
Thank you very much!
