### ISSUE TITLE
Regenerating an expired certificate

### ISSUE THREAD

**Issue by willgmcc** [Cofyc/dnscrypt-wrapper#66]
Recently, the first certificate that I created with dnscrypt-wrapper expired, causing dnscrypt-proxy to refuse to speak to it. I fixed the problem by removing the following files:

```
rm crypt_public.key crypt_secret.key dnscrypt.cert
```
This left only `public.key` and `secret.key`. I then re-generated them with the following commands:
```
dnscrypt-wrapper --gen-crypt-keypair
dnscrypt-wrapper --crypt-secretkey-file crypt_secret.key --provider-publickey-file=public.key --provider-secretkey-file=secret.key --gen-cert-file
```
This seemed to work, but I wanted to check and see if this was the correct way to do this?

**Comment by willgmcc** [comment]
@Cofyc Is this correct?

**Comment by Cofyc** [comment]
@willgmcc Yes, it's right.
