### ISSUE TITLE
centos6下无法安装

### ISSUE THREAD

**Issue by MiuKaShi** [cofyc/dnscrypt-wrapper#78]
执行 make install 后提示错误
make[1]: Entering directory `/root/dnscrypt-wrapper/argparse'
cc -o argparse.o -c  -Wall -O3 -g -ggdb -fPIC argparse.c
ar rcs libargparse.a argparse.o
make[1]: Leaving directory`/root/dnscrypt-wrapper/argparse'
  LINK dnscrypt-wrapper
udp_request.o: In function `udp_request_kill':
udp_request.c:(.text+0x3f): undefined reference to`event_get_callback_arg'
udp_request.c:(.text+0x50): undefined reference to `event_free'
udp_request.c:(.text+0x66): undefined reference to`event_free'
udp_request.o: In function `udp_listener_stop':
udp_request.c:(.text+0x5ec): undefined reference to`event_free'
udp_request.o: In function `udp_listener_start':
udp_request.c:(.text+0x658): undefined reference to`event_new'
udp_request.c:(.text+0x69b): undefined reference to `event_new'
udp_request.o: In function`sendto_with_retry':
udp_request.c:(.text+0x7aa): undefined reference to `event_get_callback_arg'
udp_request.c:(.text+0x83d): undefined reference to`event_get_callback_arg'
udp_request.c:(.text+0x873): undefined reference to `event_free'
udp_request.c:(.text+0x8cb): undefined reference to`event_get_callback_arg'
udp_request.c:(.text+0x933): undefined reference to `event_new'
udp_request.o: In function`resolver_to_proxy_cb':
udp_request.c:(.text+0xa9a): undefined reference to `evutil_sockaddr_cmp'
udp_request.o: In function`sendto_with_retry_timer_cb':
udp_request.c:(.text+0xdac): undefined reference to `event_get_fd'
udp_request.o: In function`client_to_proxy_cb':
udp_request.c:(.text+0x10e1): undefined reference to `event_new'
udp_request.o: In function`udp_listener_bind':
udp_request.c:(.text+0x1787): undefined reference to `evutil_make_socket_closeonexec'
udp_request.c:(.text+0x17e5): undefined reference to`evutil_make_socket_closeonexec'
udp_request.c:(.text+0x183a): undefined reference to `evutil_closesocket'
udp_request.c:(.text+0x1881): undefined reference to`evutil_closesocket'
tcp_request.o: In function `tcp_listener_start':
tcp_request.c:(.text+0x11): undefined reference to`evconnlistener_enable'
tcp_request.o: In function `tcp_listener_bind':
tcp_request.c:(.text+0x112): undefined reference to`evconnlistener_new'
tcp_request.c:(.text+0x12a): undefined reference to `evconnlistener_disable'
tcp_request.c:(.text+0x13f): undefined reference to`evconnlistener_set_error_cb'
tcp_request.c:(.text+0x170): undefined reference to `evconnlistener_free'
tcp_request.o: In function`tcp_accept_error_cb':
tcp_request.c:(.text+0x22c): undefined reference to `evconnlistener_disable'
tcp_request.c:(.text+0x277): undefined reference to`event_new'
tcp_request.o: In function `tcp_accept_timer_cb':
tcp_request.c:(.text+0x29c): undefined reference to`event_free'
tcp_request.o: In function `tcp_request_kill':
tcp_request.c:(.text+0x2e9): undefined reference to`event_free'
tcp_request.o: In function `tcp_connection_cb':
tcp_request.c:(.text+0x448): undefined reference to`bufferevent_socket_new'
tcp_request.c:(.text+0x46b): undefined reference to `bufferevent_socket_new'
tcp_request.c:(.text+0x4be): undefined reference to`event_new'
tcp_request.c:(.text+0x530): undefined reference to `bufferevent_socket_connect'
tcp_request.c:(.text+0x59c): undefined reference to`evutil_closesocket'
tcp_request.o: In function `tcp_listener_stop':
tcp_request.c:(.text+0x65c): undefined reference to`evconnlistener_free'
tcp_request.o: In function `resolver_proxy_read_cb':
tcp_request.c:(.text+0x6b3): undefined reference to`bufferevent_get_input'
tcp_request.c:(.text+0x6f9): undefined reference to `evbuffer_get_length'
tcp_request.c:(.text+0x712): undefined reference to`evbuffer_pullup'
tcp_request.c:(.text+0x814): undefined reference to `evbuffer_get_length'
tcp_request.o: In function`proxy_resolver_event_cb':
tcp_request.c:(.text+0x911): undefined reference to `bufferevent_getfd'
tcp_request.o: In function`client_proxy_read_cb':
tcp_request.c:(.text+0x95d): undefined reference to `bufferevent_get_input'
tcp_request.c:(.text+0x988): undefined reference to`evbuffer_get_length'
tcp_request.c:(.text+0x9d7): undefined reference to `evbuffer_remove_buffer'
tcp_request.c:(.text+0xb5c): undefined reference to`evbuffer_get_length'
tcp_request.o: In function `tcp_accept_timer_cb':
tcp_request.c:(.text+0x2b4): undefined reference to`evconnlistener_enable'
main.o: In function `sockaddr_from_ip_and_port.clone.0':
main.c:(.text+0x185): undefined reference to`evutil_parse_sockaddr_port'
main.c:(.text+0x1cd): undefined reference to `evutil_parse_sockaddr_port'
collect2: ld returned 1 exit status
make: **\* [dnscrypt-wrapper] Error 1

**Comment by MiuKaShi** [comment]
追加：内核是3.12.9-x86_64-linode37

**Comment by cofyc** [comment]
hi,

看错误日志是找不到 libevent 的函数。

1, 确认下 libevent 是否已安装：`yum list libevent`

2, 如果已安装，还是找不到 libevent，可能 libevent 不是安装在默认位置，可以附加 LDFLAGS/CFLAGS 来编译：

```
# 比如 libevent 是安装在 /usr/local 下的话
$ make LDFLAGS='-L/usr/local/lib/' CFLAGS=-I/usr/local/include/
```

**Comment by MiuKaShi** [comment]
还是不行， libsodium 安装的是最新的1.0.10版本，libevent是2.1.5beta版本，执行make install后提示同样错误。libevent查询结果如下：
[root@MiuKaShi ~]# ls -al /usr/lib |grep libevent
lrwxrwxrwx  1 root root      21 Jul 21 12:32 libevent-2.1.so.1 -> libevent-2.1.so.1.0.0
-rwxr-xr-x  1 root root  449855 Jul 12 11:05 libevent-2.1.so.1.0.0
lrwxrwxrwx  1 root root      21 Jul 21 12:32 libevent-2.1.so.5 -> libevent-2.1.so.5.0.0
-rwxr-xr-x  1 root root 1102615 Jul 21 12:32 libevent-2.1.so.5.0.0
-rw-r--r--  1 root root 1778662 Jul 21 12:32 libevent.a
lrwxrwxrwx  1 root root      26 Jul 12 11:05 libevent_core-2.1.so.1 -> libevent_core-2.1.so.1.0.0
-rwxr-xr-x  1 root root  279187 Jul 12 11:05 libevent_core-2.1.so.1.0.0
lrwxrwxrwx  1 root root      26 Jul 21 12:32 libevent_core-2.1.so.5 -> libevent_core-2.1.so.5.0.0
-rwxr-xr-x  1 root root  704301 Jul 21 12:32 libevent_core-2.1.so.5.0.0
-rw-r--r--  1 root root 1165188 Jul 21 12:32 libevent_core.a
-rwxr-xr-x  1 root root     970 Jul 21 12:32 libevent_core.la
lrwxrwxrwx  1 root root      26 Jul 21 12:32 libevent_core.so -> libevent_core-2.1.so.5.0.0
lrwxrwxrwx  1 root root      27 Jul 12 11:05 libevent_extra-2.1.so.1 -> libevent_extra-2.1.so.1.0.0
-rwxr-xr-x  1 root root  190303 Jul 12 11:05 libevent_extra-2.1.so.1.0.0
lrwxrwxrwx  1 root root      27 Jul 21 12:32 libevent_extra-2.1.so.5 -> libevent_extra-2.1.so.5.0.0
-rwxr-xr-x  1 root root  420325 Jul 21 12:32 libevent_extra-2.1.so.5.0.0
-rw-r--r--  1 root root  613546 Jul 21 12:32 libevent_extra.a
-rwxr-xr-x  1 root root     977 Jul 21 12:32 libevent_extra.la
lrwxrwxrwx  1 root root      27 Jul 21 12:32 libevent_extra.so -> libevent_extra-2.1.so.5.0.0
-rwxr-xr-x  1 root root     935 Jul 21 12:32 libevent.la
lrwxrwxrwx  1 root root      29 Jul 12 11:05 libevent_openssl-2.1.so.1 -> libevent_openssl-2.1.so.1.0.0
-rwxr-xr-x  1 root root   32550 Jul 12 11:05 libevent_openssl-2.1.so.1.0.0
lrwxrwxrwx  1 root root      29 Jul 21 12:32 libevent_openssl-2.1.so.5 -> libevent_openssl-2.1.so.5.0.0
-rwxr-xr-x  1 root root   97400 Jul 21 12:32 libevent_openssl-2.1.so.5.0.0
-rw-r--r--  1 root root  136906 Jul 21 12:32 libevent_openssl.a
-rwxr-xr-x  1 root root    1006 Jul 21 12:32 libevent_openssl.la
lrwxrwxrwx  1 root root      29 Jul 21 12:32 libevent_openssl.so -> libevent_openssl-2.1.so.5.0.0
lrwxrwxrwx  1 root root      30 Jul 12 11:05 libevent_pthreads-2.1.so.1 -> libevent_pthreads-2.1.so.1.0.0
-rwxr-xr-x  1 root root   10486 Jul 12 11:05 libevent_pthreads-2.1.so.1.0.0
lrwxrwxrwx  1 root root      30 Jul 21 12:32 libevent_pthreads-2.1.so.5 -> libevent_pthreads-2.1.so.5.0.0
-rwxr-xr-x  1 root root   18430 Jul 21 12:32 libevent_pthreads-2.1.so.5.0.0
-rw-r--r--  1 root root   18670 Jul 21 12:32 libevent_pthreads.a
-rwxr-xr-x  1 root root     998 Jul 21 12:32 libevent_pthreads.la
lrwxrwxrwx  1 root root      30 Jul 21 12:32 libevent_pthreads.so -> libevent_pthreads-2.1.so.5.0.0
lrwxrwxrwx  1 root root      21 Jul 21 12:32 libevent.so -> libevent-2.1.so.5.0.0

**Comment by cofyc** [comment]
我在 6.5 下测试 OK:

- 从这里下载：https://github.com/cofyc/dnscrypt-wrapper/releases
- 安装 libevent2 和 sodium：yum install -y libsodium-devel libevent2-devel
- 再按标准 linux 程序编译流程编译：make configure; ./configure; make; make install

下面是我安装日志：

```
[root@centos6 ~]# cat /etc/issue | grep release
CentOS release 6.5 (Final)
[root@centos6 ~]# wget https://github.com/cofyc/dnscrypt-wrapper/releases/download/v0.2.1/dnscrypt-wrapper-v0.2.1.tar.bz2
...snip...
2016-07-31 07:23:57 (72.1 KB/s) - “dnscrypt-wrapper-v0.2.1.tar.bz2” saved [45390/45390]
[root@centos6 ~]# tar -xvf dnscrypt-wrapper-v0.2.1.tar.bz2 && cd dnscrypt-wrapper-v0.2.1
...snip...
[root@centos6 dnscrypt-wrapper-v0.2.1]# 
[root@centos6 ~]# yum install -y libsodium-devel libevent2-devel
...snip...
Installed:
  libevent2-devel.x86_64 0:2.0.21-2.el6             libsodium-devel.x86_64 0:0.4.5-3.el6            

Complete!
[root@centos6 dnscrypt-wrapper-v0.2.1]# make
  GEN configure
  GEN config.status
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --no-create --no-recursion
checking for gcc... gcc
...snip...
  LINK dnscrypt-wrapper
```

仍然还不行的话，可以尝试新的 centos6 下测试，以上是在新建的环境下测试，编译安装是没有任何问题。

**Comment by cofyc** [comment]
@MiuKaShi 之后是 ok 了吗？issue 我先关闭，有问题再打开。
