### ISSUE TITLE
Incorrect date in logs

### ISSUE THREAD

**Issue by lenage** [cofyc/dnscrypt-wrapper#79]
Hi @cofyc ,

Thanks for awesome work, 
I just install a dnscrypt-proxy server today with docker images, 
and found there was an error in log file.  

```
Jul 30 14:42:02 lenbox dnscrypt-proxy[18666]: [INFO] This certificate is valid
Jul 30 14:42:02 lenbox dnscrypt-proxy[18666]: [INFO] Chosen certificate #1469859743 is valid from [2016-07-31] to [2016-07-32]
```

As far as i know, thers is no 2016-07-32 exist. :joy: 

Not a big issue through, I will submit a PR if get some time.

**Comment by lenage** [comment]
seem like its printed by https://github.com/jedisct1/dnscrypt-proxy/blob/bb40c7fd832b0b34bdb991101a47ed430b3750da/src/proxy/cert.c#L198

and just using `ts_end_tm.tm_mday + 1` caused this issue.

**Comment by cofyc** [comment]
Thanks! Send me PR if you have time ;-)

**Comment by cofyc** [comment]
Close this issue because it's releated to [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy/).
