### ISSUE TITLE
nslookup: can't resolve 'fbcdn-profile-a.akamaihd.net': Name or service not known

### ISSUE THREAD

**Issue by chor** [cofyc/dnscrypt-wrapper#82]
while wrapper using this  --resolver-address=203.80.96.10, client lookup fbcdn-profile-a.akamaihd.net  return Name or service not known .
change to --resolver-address=8.8.8.8 work fine,
and 'nslookup fbcdn-profile-a.akamaihd.net 203.80.96.10' on server site work fine too

**Comment by cofyc** [comment]
hi, @chor

In my test environment, I can resolve fbcdn-profile-a.akamaihd.net with dnscrypt-wrapper (203.80.96.10 as resolver address).

Please try latest release https://github.com/cofyc/dnscrypt-wrapper/releases/tag/v0.3, if you still have problem, open this issue again.
