### ISSUE TITLE
Unify dnscrypt-{proxy,wrapper} 

### ISSUE THREAD

**Issue by chantra** [cofyc/dnscrypt-wrapper#96]
Opening this task for more visibility. @cofyc more detail available in https://github.com/jedisct1/dnscrypt-proxy/issues/503

**Comment by chantra** [comment]
@cofyc what's your thought?

**Comment by cofyc** [comment]
Hi,

Sorry for late reply.

I think there is no need to add dnscrypt lib in this small project (https://github.com/cofyc/dnscrypt-wrapper/pull/94).

You can try to merge dnscrypt-wrapper into dnscrypt-proxy (https://github.com/jedisct1/dnscrypt-proxy/issues/503#issuecomment-266805923).

After you finish it, this repo will be deprecated and remains for backward compatible.

dnscrypt-proxy build scripts support windows, maybe it's easier way to support windows (https://github.com/cofyc/dnscrypt-wrapper/issues/1).

**Comment by chantra** [comment]
Thanks @cofyc 

> I think there is no need to add dnscrypt lib in this small project (#94).

The goal of this library is more so other implementations can reuse it rather than re-implement it. I understand that for dnscrypt-{wrapper,proxy} themselve there is little value though.
