### ISSUE TITLE
cygwin64 compile error and fix

### ISSUE THREAD

**Issue by rampageX** [cofyc/dnscrypt-wrapper#98]
New git version compile on Windows10 + cygwin64 will cause error:

> error: �±SA_ONSTACK�² undeclared (first use in this function)

Fix:
add
```
#ifdef __CYGWIN__
#ifndef SA_ONSTACK
#define SA_ONSTACK 0x08000000
#endif
#endif
```
to debug.c

from: https://github.com/antirez/redis/issues/232

**Comment by cofyc** [comment]
@rampageX
Can you send me a PR for this fix? I don't have CYGWIN environment to test it.

**Comment by rampageX** [comment]
@cofyc done.
